image: registry.gitlab.com/berniwittmann/beachanmeldung:latest

services:
    - postgres:latest

variables:
    SECRET_KEY: test-secret
    POSTGRES_DB: beachtest
    POSTGRES_USER: beachtest
    POSTGRES_PASSWORD: beachtest
    LANGUAGE_CODE: en-us
    TIME_ZONE: Europe/Berlin
    DEFAULT_EMAIL_FROM: test@beach.handballismaning.de
    SERVER_EMAIL: test@beach.handballismaning.de.de

deploy:
    before_script:
    - cd web/vueapp
    - npm run build
    - cd ../../
    - wget -qO- https://cli-assets.heroku.com/install-ubuntu.sh | sh
    script:
    - heroku container:login
    - heroku container:push web