image: registry.gitlab.com/berniwittmann/beachanmeldung:latest

services:
    - postgres:latest

variables:
    SECRET_KEY: test-secret
    POSTGRES_DB: beachtest
    POSTGRES_USER: beachtest
    POSTGRES_PASSWORD: beachtest
    LANGUAGE_CODE: en-us
    TIME_ZONE: Europe/Berlin
    DEFAULT_EMAIL_FROM: test@beach.handballismaning.de
    SERVER_EMAIL: test@beach.handballismaning.de.de

deploy:
    before_script:
    - apt-get update -qy
    - apt-get install -y git-all curl
    - apt-get install -y ruby-dev
    - gem install dpl
    - cd web/vueapp
    - npm install
    - npm run build
    script:
    - ls
    - dpl --provider=heroku --app=beachanmeldung --api-key=$HEROKU_PRODUCTION_API_KEY