# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-17 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20171211_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='receive_notifications',
            field=models.BooleanField(default=False, help_text='Receive a Email Notification when a new team is created', verbose_name='Receive Signup Notifications'),
        ),
    ]
