# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-12 17:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('beachname', models.CharField(max_length=400)),
                ('date_signup', models.DateTimeField(default=django.utils.timezone.now)),
                ('state', models.CharField(choices=[('waiting', 'waiting'), ('signed up', 'signed up'), ('needs approval', 'needs approval'), ('denied', 'denied')], default='needs approval', max_length=50)),
                ('paid', models.BooleanField(default=False)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
