# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 21:01
from __future__ import unicode_literals

from django.db import migrations
import stdimage.models
import stdimage.utils


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='image',
            field=stdimage.models.StdImageField(blank=True, upload_to=stdimage.utils.UploadToClassNameDirUUID()),
        ),
    ]
