# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-12 17:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0006_tournament_number_of_places'),
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='tournament',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='tournaments.Tournament'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='team',
            name='beachname',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
