# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-13 09:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0006_tournament_number_of_places'),
        ('team', '0002_auto_20171112_1827'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='team',
            unique_together=set([('tournament', 'name', 'beachname')]),
        ),
    ]
