# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-27 12:12
from __future__ import unicode_literals

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0003_auto_20171113_1045'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=200)),
                ('number', models.PositiveIntegerField()),
                ('year_of_birth', models.PositiveIntegerField(help_text='Use the following format: <YYYY>', validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2017)])),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='team.Team')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='player',
            unique_together=set([('team', 'name', 'first_name')]),
        ),
    ]
