# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-11 11:49
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_auto_20171128_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='first_name',
            field=models.CharField(help_text='First Name of the player', max_length=200, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='player',
            name='last_name',
            field=models.CharField(help_text='Last Name of the player', max_length=200, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='player',
            name='number',
            field=models.PositiveIntegerField(help_text='shirt number of the player', verbose_name='Number'),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(help_text='Team associated with the player', on_delete=django.db.models.deletion.CASCADE, related_name='players', to='team.Team', verbose_name='Team'),
        ),
        migrations.AlterField(
            model_name='player',
            name='year_of_birth',
            field=models.PositiveIntegerField(help_text='Use the following format: YYYY', validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2017)], verbose_name='Year of Birth'),
        ),
    ]
