# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-30 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('gender', models.CharField(choices=[('0', 'female'), ('1', 'male'), ('2', 'mixed')], max_length=1)),
            ],
        ),
    ]
