# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-30 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_auto_20171030_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='gender',
            field=models.CharField(choices=[('female', 'female'), ('male', 'male'), ('mixed', 'mixed')], max_length=10),
        ),
    ]
