# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-31 16:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0004_auto_20171030_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='start_signup',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
