# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-11 11:49
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import django.utils.timezone
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0006_tournament_number_of_places'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='advertisement_url',
            field=models.URLField(blank=True, help_text='Url to the Advertisement', null=True, verbose_name='Advertisement Url'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Contact Email Address for the tournament', max_length=254, null=True, verbose_name='Contact Email'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='deadline_edit',
            field=models.DateTimeField(help_text='Date by which the Edit by trainers is not possible anymore', verbose_name='Deadline for Editing'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='deadline_signup',
            field=models.DateTimeField(help_text='Date when the Signup period ends', verbose_name='End of the Signup Period'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='end_date',
            field=models.DateField(help_text='The last day when the tournament takes place', verbose_name='End Date of the Tournament'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='gender',
            field=models.CharField(choices=[(b'female', b'female'), (b'male', b'male'), (b'mixed', b'mixed')], help_text='Choose a gender for the tournament (female, male, mixed)', max_length=10, verbose_name='Tournament Gender'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='name',
            field=models.CharField(help_text='Name of the Tournament', max_length=120, verbose_name='Tournament Name'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='number_of_places',
            field=models.PositiveIntegerField(help_text='Count of possible teams that can take place in the tournament', verbose_name='Numer of Places'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='start_date',
            field=models.DateField(help_text='The first day when the tournament takes place', verbose_name='Start Date of the Tournament'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='start_signup',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date when the Signup period starts', verbose_name='Start of the Signup Period'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='starting_fee',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), default_currency='EUR', help_text='Initial required payment', max_digits=10, verbose_name='Signup Fee'),
        ),
    ]
