# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-23 18:01
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0007_auto_20171211_1249'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='Url to Additional Document', verbose_name='Additional Document Url')),
                ('name', models.CharField(help_text='Name of the Document', max_length=120, verbose_name='Document Name')),
            ],
        ),
        migrations.AlterModelOptions(
            name='tournament',
            options={'verbose_name': 'Tournament', 'verbose_name_plural': 'Tournaments'},
        ),
        migrations.AddField(
            model_name='additionaldocument',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='tournaments.Tournament'),
        ),
    ]
