# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-23 18:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0008_auto_20180123_1901'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='additionaldocument',
            options={'verbose_name': 'Additional Document', 'verbose_name_plural': 'Additional Documents'},
        ),
    ]
