# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-29 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0009_auto_20180123_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionaldocument',
            name='url',
            field=models.URLField(help_text='Url to Document', verbose_name='Document Url'),
        ),
    ]
